CREATE TABLE IF NOT EXISTS users (
    id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email         text NOT NULL,
    password_hash text NOT NULL,
    created_at    text NOT NULL
);

-- SQLite got case-insensitive uniqueness from COLLATE NOCASE. Postgres has no
-- such collation on a plain column, so uniqueness is enforced on lower(email)
-- and every lookup goes through lower(email) to use this index.
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_email_lower ON users (lower(email));

CREATE TABLE IF NOT EXISTS applications (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    bigint NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    company    text NOT NULL,
    role       text NOT NULL,
    link       text NOT NULL DEFAULT '',
    location   text NOT NULL DEFAULT '',
    notes      text NOT NULL DEFAULT '',
    status     text NOT NULL DEFAULT 'applied',
    applied_on text NOT NULL,
    created_at text NOT NULL,
    updated_at text NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_applications_user_status
    ON applications (user_id, status);
CREATE INDEX IF NOT EXISTS idx_applications_user_applied_on
    ON applications (user_id, applied_on DESC);
